SneaksAndData/arcane-framework-scala

build.sbt

Since logback 1.5.x relies on sl4j2, we should also use ZIO with sl4j2 integration

Use sl4j2 integration for ZIO

---

src/main/scala/services/consumers/SqlServerChangeTracking.scala
src/main/scala/services/consumers/StagedBatch.scala
src/main/scala/services/consumers/SynapseLink.scala
src/main/scala/services/streaming/processors/MergeProcessor.scala

Part of https://github.com/SneaksAndData/arcane-framework-scala/issues/23
This refactoring is required to simplify working with the instances of the `StagedBatch` class

Remove type parameter from the StagedBatch trait

---

src/main/scala/services/consumers/StagedBatch.scala
src/main/scala/services/consumers/SynapseLink.scala

Part of #23
Added the common interface for the `StagedBackfillMergeBatch` and `StagedBackfillOverwriteBatch`.

Add common interface for all backfill batches

---

src/main/scala/models/ArcaneSchema.scala
src/main/scala/models/settings/ArchiveTableSettings.scala
src/main/scala/models/settings/OptimizeSettings.scala
src/main/scala/models/settings/OrphanFilesExpirationSettings.scala
src/main/scala/models/settings/SnapshotExpirationSettings.scala
src/main/scala/services/consumers/SqlServerChangeTracking.scala
src/main/scala/services/consumers/StagedBatch.scala
src/main/scala/services/consumers/SynapseLink.scala
src/main/scala/services/streaming/consumers/IcebergStreamingConsumer.scala
src/test/scala/services/consumers/SqlServerChangeTrackingTests.scala
src/test/scala/services/consumers/SynapseLinkTests.scala

Part of #29
To be able to archive batches with different schemas, we need to provide the actual schema to archive expression.
Old version of the `archiveExpr` method to be removed in next PRs

Add schema to reduce expression in archiveExpr method

---

src/main/scala/models/cdm/SimpleCdmModel.scala
src/main/scala/services/base/SchemaProvider.scala
src/main/scala/services/cdm/CdmSchemaProvider.scala
src/main/scala/services/cdm/SourceCleanupRequest.scala
src/main/scala/services/mssql/MsSqlConnection.scala
src/main/scala/services/streaming/consumers/IcebergBackfillConsumer.scala
src/main/scala/services/streaming/consumers/IcebergStreamingConsumer.scala
src/test/scala/services/cdm/CmdSchemaProviderTests.scala
src/test/scala/services/connectors/mssql/MsSqlConnectorsTests.scala

Part of #29
Implemented:
- CdmSchemaProvider was moved from synapse link repository.
- Interface in the `SchemaProvider` trait was changed to use ZIO Task instead of future.
- The `apply` method of the `SimpleCdmModel` now returns the model instead of `Future[model]`

Move Cdm Schema provider

---

src/main/scala/services/lakehouse/IcebergS3CatalogWriter.scala
src/main/scala/services/streaming/processors/transformers/StagingProcessor.scala

Fixes #49.
Implemented:
- IcebergCatalogWriter is being initialized during the construction process.
- Add error logging

Fix CatalogWriter behavior

---

build.sbt
populate-cdm-container.py
src/main/scala/models/ArcaneSchema.scala
src/main/scala/services/base/FrozenSchemaProvider.scala
src/main/scala/services/cdm/AzureBlobStorageReaderExtensions.scala
src/main/scala/services/cdm/CdmSchemaProvider.scala
src/main/scala/services/cdm/CdmTableStream.scala
src/main/scala/services/merging/JdbcMergeServiceClient.scala
src/main/scala/services/mssql/MsSqlConnection.scala
src/test/scala/services/cdm/AzureBlobStorageReaderExtensionsTests.scala
src/test/scala/services/cdm/CmdSchemaProviderTests.scala
src/test/scala/services/cdm/TableFilesStreamSourceTests.scala

This is a permanent fix for https://github.com/SneaksAndData/arcane-stream-microsoft-synapse-link/pull/92
- Added the `FrozenSchemaProvider` trait that should be used in every case where we need to cache schema for multiple calls.

Add frozen schema provider

---

src/main/scala/models/DataCell.scala
src/main/scala/services/app/GenericStreamRunnerService.scala
src/main/scala/services/cdm/CdmTableStream.scala
src/main/scala/services/filters/FieldsFilteringService.scala
src/main/scala/services/streaming/base/GroupingTransformer.scala
src/main/scala/services/streaming/base/HookManager.scala
src/main/scala/services/streaming/base/MetadataEnrichedRowStreamElement.scala
src/main/scala/services/streaming/base/RowGroupTransformer.scala
src/main/scala/services/streaming/base/RowProcessor.scala
src/main/scala/services/streaming/base/StreamDataProvider.scala
src/main/scala/services/streaming/base/StreamingGraphBuilder.scala
src/main/scala/services/streaming/graph_builders/base/GenericStreamingGraphBuilder.scala
src/main/scala/services/streaming/processors/GenericGroupingTransformer.scala
src/main/scala/services/streaming/processors/transformers/FieldFilteringTransformer.scala
src/main/scala/services/streaming/processors/transformers/StagingProcessor.scala
src/test/scala/services/streaming/GenericStreamRunnerServiceTests.scala
src/test/scala/utils/TestFieldSelectionRuleSettings.scala
src/test/scala/utils/TestGroupingSettings.scala

Part of  #29
- Generalized `StreamRunnerService` interface and corresponding class.
- Generalized `StreamingGraphBuilder` interface and corresponding class.
- Added unit tests.
- Simplified couple of the generic interfaces.

Generalize the StreamingGraphBuilder

---

src/main/scala/services/streaming/base/BatchConsumer.scala
src/main/scala/services/streaming/base/StagedBatchProcessor.scala
src/main/scala/services/streaming/base/StreamingBatchProcessor.scala

This is partial rollback of #68
The Microsoft Synapse Link Arcane plugin references two deleted interfaces and we need to get them back for a short period of time.
Restored interfaces: `BatchConsumer`, `BatchProcessor`

Rollback deleted interfaces

---

src/main/scala/services/cdm/AzureBlobStorageReaderExtensions.scala
src/test/scala/services/cdm/AzureBlobStorageReaderExtensionsTests.scala
src/test/scala/services/cdm/TableFilesStreamSourceTests.scala
src/test/scala/services/merging/JdbcMergeServiceClientTests.scala

Fixes #87
Adding plus one hour to the `endDate` parameter and adding the unit test that is able to reproduce the problem

Fix incorrect datetime iterator

---

src/main/scala/models/settings/StagingDataSettings.scala
src/main/scala/services/app/GenericStreamRunnerService.scala
src/main/scala/services/base/TableManager.scala
src/main/scala/services/cdm/SynapseHookManager.scala
src/main/scala/services/consumers/SqlServerChangeTracking.scala
src/main/scala/services/consumers/StagedBatch.scala
src/main/scala/services/consumers/SynapseLink.scala
src/main/scala/services/merging/JdbcMergeServiceClient.scala
src/main/scala/services/mssql/MsSqlHookManager.scala
src/main/scala/services/streaming/base/HookManager.scala
src/main/scala/services/streaming/base/RowGroupTransformer.scala
src/main/scala/services/streaming/processors/transformers/StagingProcessor.scala
src/test/scala/services/consumers/SqlServerChangeTrackingTests.scala
src/test/scala/services/consumers/SynapseLinkTests.scala
src/test/scala/services/merging/JdbcMergeServiceClientTests.scala
src/test/scala/services/streaming/GenericStreamRunnerServiceTests.scala
src/test/scala/services/streaming/processors/MergeBatchProcessorTests.scala
src/test/scala/services/streaming/processors/transformers/StagingProcessorTests.scala
src/test/scala/utils/TestStagingDataSettings.scala

Part of #89
Implemented:
- The StagingProcessor reuses the same staging table for each staged batch.
- The `batchId` property is added to each instance of th MergeableBatch trait.
- The TableManager creates the staging table on the start of the stream.

Reuse the staging table for staging batches

---

src/main/scala/services/consumers/SqlServerChangeTracking.scala
src/main/scala/services/consumers/StagedBatch.scala
src/main/scala/services/consumers/SynapseLink.scala
src/main/scala/services/streaming/graph_builders/base/GenericStreamingGraphBuilder.scala
src/main/scala/services/streaming/processors/batch_processors/backfill/BackfillDisposeBatchProcessor.scala
src/main/scala/services/streaming/processors/batch_processors/backfill/BackfillMergeBatchProcessor.scala
src/main/scala/services/streaming/processors/batch_processors/streaming/DisposeBatchProcessor.scala
src/main/scala/services/streaming/processors/batch_processors/streaming/MergeBatchProcessor.scala
src/test/scala/services/streaming/GenericStreamRunnerServiceTests.scala
src/test/scala/services/streaming/processors/MergeBatchProcessorTests.scala

Implemented:
- Added BackfillDisposeBatchProcessor class
- Added BackfillMergeBatchProcessor class
- Classes `MergeBatchProcessor` and `DisposeBatchProcessor` moved to the `streaming` package
- The `StagedBackfillBatch` trait now implements `MergeableBatch`

Add backfill batch processors

---

src/main/scala/services/lakehouse/IcebergS3CatalogWriter.scala
src/main/scala/services/lakehouse/base/CatalogWriter.scala
src/test/scala/services/lakehouse/IcebergS3CatalogWriterTests.scala

Extract the `catalog` dependency from the `IcebergCatalogWriter` which makes it possible to override the catalog initialization in the stream runner process.

Extract the catalog dependency from IcebergCatalogWriter

---

src/main/scala/services/merging/JdbcMergeServiceClient.scala

Part of #100
Do not create backfill table if backfill mode is not `Overwrite`

Create backfill intermediate table only in backfill overwrite

---

src/main/scala/services/streaming/base/BackfillStreamingGraphBuilder.scala
src/main/scala/services/streaming/base/BackfillStreamingMergeDataProvider.scala
src/main/scala/services/streaming/base/BackfillStreamingOverwriteDataProvider.scala
src/main/scala/services/streaming/graph_builders/backfill/GenericBackfillMergeGraphBuilder.scala
src/main/scala/services/streaming/graph_builders/backfill/GenericBackfillOverwriteGraphBuilder.scala

This PR adds the stream graph builders for both `merge` and `overwrite` behaviors in backfill mode.

Add the graph builders for backfill streams

---

build.sbt
src/main/resources/logback.xml
src/main/scala/services/lakehouse/IcebergS3CatalogWriter.scala
src/main/scala/services/streaming/data_providers/backfill/GenericBackfillStreamingMergeDataProvider.scala
src/main/scala/services/streaming/processors/transformers/StagingProcessor.scala
src/test/scala/services/lakehouse/IcebergS3CatalogWriterTests.scala
src/test/scala/services/streaming/GenericStreamRunnerServiceTests.scala
src/test/scala/services/streaming/data_providers/backfill/GenericBackfillStreamingMergeDataProviderTests.scala
src/test/scala/services/streaming/data_providers/backfill/GenericBackfillStreamingOverwriteDataProviderTests.scala
src/test/scala/services/streaming/processors/transformers/StagingProcessorTests.scala

- Changed IcebergS3Writer to be provided via [reloadable service](https://zio.dev/reference/service-pattern/reloadable-services/)
- Moved `RESTCatalog` creation back to IcebergS3Writer
- Updated StagingProcessor tests to use ZIO test framework, as an example for test migrations

Add auto-reload capability for IcebergWriter and introduce ZIO Test

---

src/main/scala/extensions/StringExtensions.scala
src/main/scala/logging/ZIOLogAnnotations.scala
src/test/scala/extensions/StringExtensionTests.scala

Part of https://github.com/SneaksAndData/arcane-stream-sqlserver-change-tracking/issues/142
This is small change related to metrics and logs collection: convert all camel-case values to snake case to improve readability in datadog.
Added the `Application` property to logs and added documentation for default log annotations.

Convert the default log annotations to snake case

---

build.sbt
src/main/scala/services/streaming/processors/transformers/StagingProcessor.scala
src/main/scala/utils/CollectionUtils.scala

- Improve row grouping performance (by schema) by performing the grouping operating using `.par` (Scala parallel collections)
This addresses performance degradation when loading very wide tables (250+ columns). However, this is more of a bandaid rather than a proper fix. For example, SQL server streams do not require this operation at all, since they can only emit a single schema.
In general, framework should handle this and ideally not require schema grouping for sources that emit single schema only.

Use parallel collections when grouping rows by schema

---

src/main/scala/services/streaming/graph_builders/GenericStreamingGraphBuilder.scala
src/main/scala/services/streaming/processors/transformers/FieldFilteringTransformer.scala

- Add `.bufferUnbounded` to the staging processor - allowing data provider to keep feeding rows while the batch is merged

Use unbounded buffering to increase processing throughput

---

src/main/resources/get_select_all_query_date_partitioned.sql
src/main/resources/get_select_delta_query_date_partitioned.sql
src/main/scala/services/mssql/MsSqlConnection.scala
src/main/scala/services/mssql/QueryProvider.scala
src/test/scala/services/connectors/mssql/MsSqlConnectorsTests.scala
src/test/scala/services/connectors/mssql/MsSqlDataProviderTests.scala

- Utilize `setFetchSize` to increase throughput and expose it via connection options
- Minor refactoring
- Remove `DATE_PARTITION_FIELD` etc since deprecated

Allow setting fetch size for SQL streams

---

src/main/scala/models/settings/SourceBufferingSettings.scala
src/main/scala/services/streaming/graph_builders/GenericStreamingGraphBuilder.scala
src/test/scala/services/streaming/GenericStreamRunnerServiceTests.scala
src/test/scala/services/streaming/data_providers/backfill/GenericBackfillStreamingMergeDataProviderTests.scala
src/test/scala/services/streaming/data_providers/backfill/GenericBackfillStreamingOverwriteDataProviderTests.scala
src/test/scala/services/streaming/graph_builders/GenericGraphBuilderFactoryTests.scala
src/test/scala/utils/TestSourceBufferingSettings.scala

This PR introduces a new settings set for stream graph builder which allows to overwrite source buffering to allow to manage trade-offs between the stream throughput and latency/memory consumption.
The trait `SourceBufferingSettings` allows to set the following buffering strategies
- `Unbounded` (default for backfills)
- `Buffering(size: int)` (fixed-size buffer with back pressure)
The default implementation to be provided by the streaming plugin is the following:
- In case of backfill buffering is enabled with the `Unbounded` strategy.
- In case of streaming, buffering is disabled, but the StreamContext allows to override settings.

Implement ability to override source buffering settings for the stream

---

src/main/scala/services/mssql/MsSqlStreamingDataProvider.scala
src/main/scala/utils/SqlUtils.scala

Resolves #163
We convert all short integers to Int since it seems that Iceberg does not support Short integer types.

Add the short type conversion

---

src/main/scala/models/settings/VersionedDataGraphBuilderSettings.scala
src/test/scala/services/connectors/mssql/MsSqlDataProviderTests.scala
src/test/scala/tests/synapse/SynapseLinkStreamingDataProviderTests.scala

Part of https://github.com/SneaksAndData/arcane-stream-microsoft-synapse-link/pull/136
We need to remove this field from framework to be able to remove it from MS Synapse CRD

Remove the changeCapturePeriod from VersionedDataGraphBuilderSettings

---

src/main/scala/services/mssql/MsSqlDataProvider.scala
src/main/scala/services/mssql/MsSqlStreamingDataProvider.scala
src/main/scala/services/mssql/query/LazyQueryResult.scala

- Replace LazyList with a custom Iterator to avoid memory buildup when a query returns high number of rows
Final fix is to convert to ZIO: https://github.com/SneaksAndData/arcane-framework-scala/pull/171, however it takes a bit more time to get that one done, so let's hotifx for now.

Replace LazyList with an Iterator to address memory pressure

---

docker-compose.yaml
populate-s3-reader-bucket.py
src/main/scala/services/blobsource/BlobSourceHookManager.scala
src/main/scala/services/blobsource/base/BlobSourceDataProvider.scala
src/main/scala/services/blobsource/base/BlobSourceReader.scala
src/main/scala/services/storage/base/BlobStorageReader.scala
src/main/scala/services/storage/models/s3/S3ClientSettings.scala
src/main/scala/services/storage/models/s3/S3ModelConversions.scala
src/main/scala/services/storage/models/s3/S3StoragePath.scala
src/main/scala/services/storage/services/azure/AzureBlobStorageReader.scala
src/main/scala/services/storage/services/s3/S3BlobStorageReader.scala
src/test/scala/tests/s3/S3BlobStorageReaderTests.scala
src/test/scala/tests/services/storage/models/amazon/AmazonS3StoragePathTests.scala
src/test/scala/tests/shared/S3StorageInfo.scala

Part of #175 
- Add implementation of `BlobStorageReader` for S3
- Add tests for stream prefixes and blob exists
- Add stream blob content overload that returns a stream of bytes rather that a stream of text
- Add writer implementation to support object deletion
- Fully test all methods available in S3 reader

[Parquet Source] Add S3 Blob Reader Implementation
